name: Proto-go-generator
on:
  pull_request:
    paths:
    - 'internal/opentelemetry-proto'

jobs:
  protogen:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
      with:
        ref: ${{ github.head_ref }}
        submodules: true
    - uses: actions/setup-go@v2
      with:
        go-version: '^1.14.0'
    - run: make protobuf
    - uses: stefanzweifel/git-auto-commit-action@v4
      id: commit-changes
      with:
        commit_message: Auto-fix go.sum changes in dependent modules
